import { supabaseAdmin } from '../../config/supabase';
import { Database } from '../../config/supabase';
import QRCode from 'qrcode';

type ReferralLink = Database['public']['Tables']['referral_links']['Row'];
type ReferralLinkInsert = Database['public']['Tables']['referral_links']['Insert'];
type ReferralLinkUpdate = Database['public']['Tables']['referral_links']['Update'];
type Click = Database['public']['Tables']['clicks']['Row'];

export class SupabaseReferralLinkService {
  /**
   * Create a new referral link
   */
  static async createReferralLink(
    userId: string,
    customMessage?: string,
    metadata?: any
  ): Promise<ReferralLink> {
    try {
      const companyUrl = process.env.COMPANY_URL || 'https://instabids.ai';
      const baseUrl = process.env.BASE_URL || 'http://localhost:5000';
      
      // Check if user already has a primary link
      const { data: existingLink } = await supabaseAdmin
        .from('referral_links')
        .select('*')
        .eq('user_id', userId)
        .eq('is_primary', true)
        .single();

      // If user has a primary link, set it to non-primary
      if (existingLink) {
        await supabaseAdmin
          .from('referral_links')
          .update({ is_primary: false })
          .eq('id', existingLink.id);
      }

      // Create new referral link (short_code will be auto-generated by trigger)
      const linkData: ReferralLinkInsert = {
        user_id: userId,
        original_url: companyUrl,
        company_url: companyUrl,
        custom_message: customMessage,
        metadata: metadata || {},
        statistics: {}, // Will be populated with click data
        is_primary: true,
        is_active: true,
        expires_at: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days from now
        qr_code: '' // Will be generated after insert
      };

      const { data: link, error } = await supabaseAdmin
        .from('referral_links')
        .insert(linkData)
        .select()
        .single();

      if (error) throw error;

      // Generate QR code with the actual destination URL
      const companyUrl = process.env.COMPANY_URL || 'https://instabids.ai';
      const qrCodeUrl = `${companyUrl}?ref=${link.short_code}`;
      const qrCode = await QRCode.toDataURL(qrCodeUrl);

      // Update link with QR code
      const { data: updatedLink, error: updateError } = await supabaseAdmin
        .from('referral_links')
        .update({ qr_code: qrCode })
        .eq('id', link.id)
        .select()
        .single();

      if (updateError) throw updateError;

      return updatedLink;
    } catch (error) {
      console.error('Error creating referral link:', error);
      throw error;
    }
  }

  /**
   * Get user's primary referral link
   */
  static async getPrimaryLink(userId: string): Promise<ReferralLink | null> {
    try {
      const { data, error } = await supabaseAdmin
        .from('referral_links')
        .select('*')
        .eq('user_id', userId)
        .eq('is_primary', true)
        .eq('is_active', true)
        .single();

      if (error) {
        if (error.code === 'PGRST116') return null; // No rows found
        throw error;
      }

      // Check if link is expired
      if (data && data.expires_at && new Date(data.expires_at) < new Date()) {
        // Mark as inactive if expired
        await supabaseAdmin
          .from('referral_links')
          .update({ is_active: false })
          .eq('id', data.id);
        return null;
      }

      return data;
    } catch (error) {
      console.error('Error getting primary link:', error);
      throw error;
    }
  }

  /**
   * Get all user's referral links
   */
  static async getUserLinks(userId: string): Promise<ReferralLink[]> {
    try {
      const { data, error } = await supabaseAdmin
        .from('referral_links')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      if (error) throw error;

      return data || [];
    } catch (error) {
      console.error('Error getting user links:', error);
      throw error;
    }
  }

  /**
   * Get referral link by short code
   */
  static async getLinkByShortCode(shortCode: string): Promise<ReferralLink | null> {
    try {
      const { data, error } = await supabaseAdmin
        .from('referral_links')
        .select('*')
        .eq('short_code', shortCode)
        .eq('is_active', true)
        .single();

      if (error) {
        if (error.code === 'PGRST116') return null; // No rows found
        throw error;
      }

      // Check if link is expired
      if (data && data.expires_at && new Date(data.expires_at) < new Date()) {
        return null;
      }

      return data;
    } catch (error) {
      console.error('Error getting link by short code:', error);
      throw error;
    }
  }

  /**
   * Track click on referral link
   */
  static async trackClick(
    referralLinkId: string,
    clickData: {
      ip_address: string;
      user_agent: string;
      referer?: string;
      country?: string;
      city?: string;
      region?: string;
      device?: string;
      browser?: string;
      os?: string;
      metadata?: any;
    }
  ): Promise<Click> {
    try {
      const { data: click, error } = await supabaseAdmin
        .from('clicks')
        .insert({
          referral_link_id: referralLinkId,
          ip_address: clickData.ip_address,
          user_agent: clickData.user_agent,
          referer: clickData.referer,
          country: clickData.country,
          city: clickData.city,
          region: clickData.region,
          device: clickData.device || 'unknown',
          browser: clickData.browser || 'unknown',
          os: clickData.os || 'unknown',
          metadata: clickData.metadata
        })
        .select()
        .single();

      if (error) throw error;

      // Update link statistics
      await this.updateLinkStatistics(referralLinkId);

      return click;
    } catch (error) {
      console.error('Error tracking click:', error);
      throw error;
    }
  }

  /**
   * Update link statistics
   */
  static async updateLinkStatistics(referralLinkId: string): Promise<void> {
    try {
      // Get click statistics
      const { data: clicks, error: clicksError } = await supabaseAdmin
        .from('clicks')
        .select('*')
        .eq('referral_link_id', referralLinkId);

      if (clicksError) throw clicksError;

      const totalClicks = clicks?.length || 0;
      const uniqueIps = new Set(clicks?.map(c => c.ip_address) || []);
      const uniqueClicks = uniqueIps.size;

      // Get conversion statistics
      const { data: conversions, error: convError } = await supabaseAdmin
        .from('conversions')
        .select('*')
        .eq('referral_link_id', referralLinkId);

      if (convError) throw convError;

      const totalConversions = conversions?.length || 0;
      const conversionRate = totalClicks > 0 ? (totalConversions / totalClicks) * 100 : 0;

      // Calculate device statistics
      const deviceStats = {
        mobile: 0,
        desktop: 0,
        tablet: 0,
        other: 0
      };

      clicks?.forEach(click => {
        const device = click.device?.toLowerCase() || 'other';
        if (device.includes('mobile')) deviceStats.mobile++;
        else if (device.includes('desktop')) deviceStats.desktop++;
        else if (device.includes('tablet')) deviceStats.tablet++;
        else deviceStats.other++;
      });

      // Calculate country statistics
      const countryStats: Record<string, number> = {};
      clicks?.forEach(click => {
        if (click.country) {
          countryStats[click.country] = (countryStats[click.country] || 0) + 1;
        }
      });

      // Update statistics in database
      const { error: updateError } = await supabaseAdmin
        .from('referral_links')
        .update({
          statistics: {
            totalClicks,
            uniqueClicks,
            conversions: totalConversions,
            conversionRate,
            lastClickedAt: clicks && clicks.length > 0 
              ? Math.max(...clicks.map(c => new Date(c.clicked_at).getTime()))
              : null,
            clicksByCountry: countryStats,
            clicksByDevice: deviceStats,
            clicksByChannel: {}
          }
        })
        .eq('id', referralLinkId);

      if (updateError) throw updateError;
    } catch (error) {
      console.error('Error updating link statistics:', error);
      throw error;
    }
  }

  /**
   * Refresh expired link for user
   */
  static async refreshLink(userId: string): Promise<ReferralLink> {
    try {
      // Get current primary link
      const { data: currentLink } = await supabaseAdmin
        .from('referral_links')
        .select('*')
        .eq('user_id', userId)
        .eq('is_primary', true)
        .single();

      // Deactivate current link if exists
      if (currentLink) {
        await supabaseAdmin
          .from('referral_links')
          .update({ is_active: false, is_primary: false })
          .eq('id', currentLink.id);
      }

      // Create new link
      return await this.createReferralLink(
        userId, 
        currentLink?.custom_message, 
        currentLink?.metadata
      );
    } catch (error) {
      console.error('Error refreshing link:', error);
      throw error;
    }
  }

  /**
   * Delete referral link
   */
  static async deleteLink(linkId: string, userId: string): Promise<void> {
    try {
      const { error } = await supabaseAdmin
        .from('referral_links')
        .delete()
        .eq('id', linkId)
        .eq('user_id', userId);

      if (error) throw error;
    } catch (error) {
      console.error('Error deleting link:', error);
      throw error;
    }
  }
}